[project]
name = "apprise-api-headless"
description = "Minimalistic version of Apprise API"
readme = "README.md"
license-files = ["LICENSE.md"]
dynamic = ["version"]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]==0.141.1",
    "prometheus-fastapi-instrumentator==8.1.0",
    "pydantic-settings==2.15.0",
]

[dependency-groups]
dev = [
    "pytest==9.1.1",
    "pytest-httpserver==1.1.5",
    "ruff==0.16.6",
    "httpx2==2.12.0",
]

[tool.setuptools]
packages = ["apprise_webhook_bridge"]

[tool.ruff.lint]
extend-select = ["E", "W", "I", "B", "Q"]

[tool.pytest.ini_options]
pythonpath = ["."]
log_cli = true
log_cli_level = "DEBUG"
